Layout/ArgumentAlignment:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Lint/RescueException:
  Enabled: false

Lint/SendWithMixinArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/Next:
  Enabled: false

Rails/RakeEnvironment:
  Exclude:
    - 'lib/tasks/foreman_kubevirt_tasks.rake'
