language: ruby
services:
  - postgresql
rvm:
  - 2.5
cache:
  - bundler
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install nodejs git libsqlite3-dev libpq-dev zlib1g-dev libvirt-dev
install:
  - unset BUNDLE_GEMFILE
  - cd ..
  - git clone https://github.com/theforeman/foreman.git -b ${FOREMAN_CORE_BRANCH} --depth 1
  - cd ${FOREMAN_PLUGIN_NAME}
  - bundle install --jobs=3 --retry=3
  - cd ../foreman
  - echo "gemspec :path => '../${FOREMAN_PLUGIN_NAME}'" > bundler.d/${FOREMAN_PLUGIN_NAME}.local.rb
  - ln -s settings.yaml.test config/settings.yaml
  - bundle install --jobs=3 --retry=3 --without journald mysql2 console journald
script:
  - export DATABASE_URL=postgresql://localhost/travis_ci_test
  - cd ../${FOREMAN_PLUGIN_NAME}
  - cd ../foreman
  - bundle exec rake db:create RAILS_ENV=test
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rake test:${FOREMAN_PLUGIN_NAME}
env:
  global:
    - TESTOPTS=-v
    - FOREMAN_PLUGIN_NAME=foreman_kubevirt
  matrix:
    - FOREMAN_CORE_BRANCH=develop
